<?php

class QubitHmtArticleLinkageException extends InvalidArgumentException
{
    private $diagnostics;

    public function __construct(array $diagnostics)
    {
        $this->diagnostics = $diagnostics;

        parent::__construct(self::formatDiagnostics($diagnostics));
    }

    public function getDiagnostics()
    {
        return $this->diagnostics;
    }

    public static function formatDiagnostics(array $diagnostics)
    {
        $messages = [];

        foreach ($diagnostics as $diagnostic) {
            $messages[] = $diagnostic['message'];
        }

        return implode(' ', array_unique($messages));
    }
}

/**
 * Plugin-owned article model.
 *
 * Manages read/write operations for the hmt_article table, which is the
 * persistence surface owned exclusively by sfHomicideMediaTrackerPlugin.
 * This class must not modify AtoM core tables directly; all cross-linking
 * with AtoM records (e.g. QubitInformationObject) is done via stored
 * identifiers only.
 *
 * Persistence contract (lane 01):
 *  - Plugin owns:  hmt_article
 *  - AtoM-linked:  atom_actor_id / atom_record_id (contract), atom_object_id (legacy alias)
 *  - Write policy: INSERT on create, UPDATE on edit; no upsert outside this class
 *  - Identifier:   UUID v4, generated by generateId()
 *  - Fallback:     hosted fallback remains available; this table is additive
 */
class QubitHmtArticle
{
    const LINKAGE_SCHEMA_COLUMNS = [
        'atom_actor_id',
        'atom_record_id',
    ];

    const LINKAGE_LOOKUP_TABLES = [
        'actor',
        'information_object',
    ];

    const ACTOR_LOOKUP_SQL = 'SELECT 1 FROM actor WHERE id = ? LIMIT 1';
    const RECORD_LOOKUP_SQL = 'SELECT 1 FROM information_object WHERE id = ? LIMIT 1';

    // Status constants
    const STATUS_DRAFT  = 'draft';
    const STATUS_ACTIVE = 'active';

    public $id;
    public $title;
    public $source;
    public $url;
    public $publicationDate;
    public $summary;
    public $status;
    public $atomActorId;
    public $atomRecordId;
    public $atomObjectId;
    public $createdAt;
    public $updatedAt;

    /**
     * Creates the hmt_article table if it does not already exist.
     * Safe to call on every request; guarded by IF NOT EXISTS.
     */
    public static function ensureTable()
    {
        $sql = <<<SQL
CREATE TABLE IF NOT EXISTS hmt_article (
  id               VARCHAR(255)  NOT NULL,
  title            VARCHAR(1024) NOT NULL DEFAULT '',
  source           VARCHAR(512)  NOT NULL DEFAULT '',
  url              TEXT,
  publication_date DATE,
  summary          TEXT,
  status           VARCHAR(50)   NOT NULL DEFAULT 'draft',
  atom_actor_id    INT           DEFAULT NULL,
  atom_record_id   INT           DEFAULT NULL,
  atom_object_id   INT           DEFAULT NULL,
  created_at       DATETIME      NOT NULL,
  updated_at       DATETIME      NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL;
        QubitPdo::modify($sql);
        self::ensureNullableIntColumn('atom_actor_id');
        self::ensureNullableIntColumn('atom_record_id');
    }

    /**
     * Retrieve a single article by primary key.
     *
     * @param  string $id
     * @return QubitHmtArticle|null
     */
    public static function getById($id)
    {
        $stmt = QubitPdo::prepareAndExecute(
            'SELECT * FROM hmt_article WHERE id = ?',
            [$id]
        );
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        return $row ? self::fromRow($row) : null;
    }

    /**
     * Return a paginated list of articles, newest first.
     *
     * @param  int $limit
     * @param  int $offset
     * @return QubitHmtArticle[]
     */
    public static function getList($limit = 25, $offset = 0)
    {
        $stmt = QubitPdo::prepareAndExecute(
            'SELECT * FROM hmt_article ORDER BY created_at DESC LIMIT ? OFFSET ?',
            [(int) $limit, (int) $offset]
        );

        $results = [];
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $results[] = self::fromRow($row);
        }

        return $results;
    }

    /**
     * Persist a new article record.
     * Sets id, created_at, and updated_at automatically if not provided.
     */
    public function insert()
    {
        if (empty($this->id)) {
            $this->id = self::generateId();
        }

        $this->assertValidLinkage();

        $now = date('Y-m-d H:i:s');
        $this->createdAt = $now;
        $this->updatedAt = $now;

        QubitPdo::prepareAndExecute(
            'INSERT INTO hmt_article
              (id, title, source, url, publication_date, summary, status, atom_actor_id, atom_record_id, atom_object_id, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $this->id,
                $this->title ?? '',
                $this->source ?? '',
                $this->url ?: null,
                $this->publicationDate ?: null,
                $this->summary ?: null,
                $this->status ?? self::STATUS_DRAFT,
                $this->atomActorId ?: null,
                $this->atomRecordId ?: null,
                $this->atomObjectId ?: null,
                $this->createdAt,
                $this->updatedAt,
            ]
        );
    }

    /**
     * Persist changes to an existing article record.
     */
    public function update()
    {
        $this->assertValidLinkage();
        $this->updatedAt = date('Y-m-d H:i:s');

        QubitPdo::prepareAndExecute(
            'UPDATE hmt_article
              SET title = ?, source = ?, url = ?, publication_date = ?, summary = ?,
                  status = ?, atom_actor_id = ?, atom_record_id = ?, atom_object_id = ?, updated_at = ?
              WHERE id = ?',
            [
                $this->title ?? '',
                $this->source ?? '',
                $this->url ?: null,
                $this->publicationDate ?: null,
                $this->summary ?: null,
                $this->status ?? self::STATUS_DRAFT,
                $this->atomActorId ?: null,
                $this->atomRecordId ?: null,
                $this->atomObjectId ?: null,
                $this->updatedAt,
                $this->id,
            ]
        );
    }

    /**
     * Delete the article record by id.
     *
     * @param  string $id
     */
    public static function deleteById($id)
    {
        QubitPdo::prepareAndExecute(
            'DELETE FROM hmt_article WHERE id = ?',
            [$id]
        );
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static function fromRow(array $row)
    {
        $obj = new self();
        $obj->id              = $row['id'];
        $obj->title           = $row['title'];
        $obj->source          = $row['source'];
        $obj->url             = $row['url'];
        $obj->publicationDate = $row['publication_date'];
        $obj->summary         = $row['summary'];
        $obj->status          = $row['status'];
        $obj->atomActorId     = array_key_exists('atom_actor_id', $row) ? $row['atom_actor_id'] : null;
        $obj->atomRecordId    = array_key_exists('atom_record_id', $row) ? $row['atom_record_id'] : null;
        $obj->atomObjectId    = array_key_exists('atom_object_id', $row) ? $row['atom_object_id'] : null;
        $obj->createdAt       = $row['created_at'];
        $obj->updatedAt       = $row['updated_at'];

        return $obj;
    }

    public static function diagnoseLinkage(array $values, callable $actorExists = null, callable $recordExists = null)
    {
        $diagnostics = [];
        $normalized = [
            'atom_actor_id' => self::normalizeNullableInt($values, 'atom_actor_id', $diagnostics),
            'atom_record_id' => self::normalizeNullableInt($values, 'atom_record_id', $diagnostics),
            'atom_object_id' => self::normalizeNullableInt($values, 'atom_object_id', $diagnostics),
        ];

        $recordAliasMismatch = null !== $normalized['atom_record_id']
            && null !== $normalized['atom_object_id']
            && $normalized['atom_record_id'] !== $normalized['atom_object_id'];

        if ($recordAliasMismatch) {
            $diagnostics[] = [
                'field' => 'atom_record_id',
                'code' => 'record_link_alias_mismatch',
                'message' => 'atom_record_id and legacy atom_object_id must reference the same archival description or one of them must be cleared.',
            ];
        }

        if (empty($diagnostics)) {
            if (null === $normalized['atom_record_id'] && null !== $normalized['atom_object_id']) {
                $normalized['atom_record_id'] = $normalized['atom_object_id'];
            }

            if (null === $normalized['atom_object_id'] && null !== $normalized['atom_record_id']) {
                $normalized['atom_object_id'] = $normalized['atom_record_id'];
            }

            $actorExists = $actorExists ?: [__CLASS__, 'atomActorExists'];
            $recordExists = $recordExists ?: [__CLASS__, 'atomRecordExists'];

            if (null !== $normalized['atom_actor_id'] && !$actorExists($normalized['atom_actor_id'])) {
                $diagnostics[] = [
                    'field' => 'atom_actor_id',
                    'code' => 'missing_actor_link_target',
                    'message' => sprintf(
                        'atom_actor_id %d does not reference an existing AtoM authority record. Clear the link or provide a valid actor id.',
                        $normalized['atom_actor_id']
                    ),
                ];
            }

            if (null !== $normalized['atom_record_id'] && !$recordExists($normalized['atom_record_id'])) {
                $diagnostics[] = [
                    'field' => 'atom_record_id',
                    'code' => 'missing_record_link_target',
                    'message' => sprintf(
                        'atom_record_id %d does not reference an existing AtoM archival description. Clear the link or provide a valid record id.',
                        $normalized['atom_record_id']
                    ),
                ];
            }
        }

        return [
            'normalized' => $normalized,
            'diagnostics' => $diagnostics,
        ];
    }

    private static function generateId()
    {
        // RFC 4122 UUID v4 using cryptographically secure randomness
        $bytes = random_bytes(16);

        // Set version bits (4) and variant bits (RFC 4122)
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);

        // Format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (8-4-4-4-12 hex chars)
        return vsprintf('%s%s%s%s-%s%s-%s%s-%s%s-%s%s%s%s%s%s', str_split(bin2hex($bytes), 2));
    }

    private function assertValidLinkage()
    {
        $result = self::diagnoseLinkage([
            'atom_actor_id' => $this->atomActorId,
            'atom_record_id' => $this->atomRecordId,
            'atom_object_id' => $this->atomObjectId,
        ]);

        if (!empty($result['diagnostics'])) {
            throw new QubitHmtArticleLinkageException($result['diagnostics']);
        }

        $this->atomActorId = $result['normalized']['atom_actor_id'];
        $this->atomRecordId = $result['normalized']['atom_record_id'];
        $this->atomObjectId = $result['normalized']['atom_object_id'];
    }

    private static function normalizeNullableInt(array $values, $field, array &$diagnostics)
    {
        if (!array_key_exists($field, $values) || null === $values[$field] || '' === $values[$field]) {
            return null;
        }

        if (!is_scalar($values[$field])) {
            $diagnostics[] = [
                'field' => $field,
                'code' => 'invalid_link_type',
                'message' => sprintf('%s must be a positive integer AtoM identifier or be left blank.', $field),
            ];

            return null;
        }

        $value = trim((string) $values[$field]);

        if (!preg_match('/^[1-9][0-9]*$/', $value)) {
            $diagnostics[] = [
                'field' => $field,
                'code' => 'invalid_link_format',
                'message' => sprintf('%s must be a positive integer AtoM identifier or be left blank.', $field),
            ];

            return null;
        }

        return (int) $value;
    }

    private static function ensureNullableIntColumn($columnName)
    {
        if (!in_array($columnName, self::LINKAGE_SCHEMA_COLUMNS, true)) {
            throw new InvalidArgumentException(sprintf('Invalid linkage schema column "%s".', $columnName));
        }

        $stmt = QubitPdo::prepareAndExecute(
            'SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?',
            ['hmt_article', $columnName]
        );

        if (!$stmt->fetchColumn()) {
            QubitPdo::modify(sprintf('ALTER TABLE hmt_article ADD COLUMN %s INT DEFAULT NULL', $columnName));
        }
    }

    private static function atomActorExists($id)
    {
        return self::databaseRecordExists('actor', $id);
    }

    private static function atomRecordExists($id)
    {
        return self::databaseRecordExists('information_object', $id);
    }

    private static function databaseRecordExists($table, $id)
    {
        if (!in_array($table, self::LINKAGE_LOOKUP_TABLES, true)) {
            throw new InvalidArgumentException(sprintf('Invalid linkage lookup table "%s".', $table));
        }

        if ('actor' === $table) {
            $sql = self::ACTOR_LOOKUP_SQL;
        } else {
            $sql = self::RECORD_LOOKUP_SQL;
        }

        $stmt = QubitPdo::prepareAndExecute($sql, [$id]);

        return false !== $stmt->fetchColumn();
    }
}
