<?php

/**
 * Plugin-owned article model.
 *
 * Manages read/write operations for the hmt_article table, which is the
 * persistence surface owned exclusively by sfHomicideMediaTrackerPlugin.
 * This class must not modify AtoM core tables directly; all cross-linking
 * with AtoM records (e.g. QubitInformationObject) is done via stored
 * identifiers only.
 *
 * Persistence contract (lane 01):
 *  - Plugin owns:  hmt_article
 *  - AtoM-linked:  atom_object_id (reference to QubitInformationObject.id, nullable)
 *  - Write policy: INSERT on create, UPDATE on edit; no upsert outside this class
 *  - Identifier:   UUID v4, generated by generateId()
 *  - Fallback:     hosted fallback remains available; this table is additive
 */
class QubitHmtArticle
{
    // Status constants
    const STATUS_DRAFT  = 'draft';
    const STATUS_ACTIVE = 'active';

    public $id;
    public $title;
    public $source;
    public $url;
    public $publicationDate;
    public $summary;
    public $status;
    public $atomObjectId;
    public $createdAt;
    public $updatedAt;

    /**
     * Creates the hmt_article table if it does not already exist.
     * Safe to call on every request; guarded by IF NOT EXISTS.
     */
    public static function ensureTable()
    {
        $sql = <<<SQL
CREATE TABLE IF NOT EXISTS hmt_article (
  id               VARCHAR(255)  NOT NULL,
  title            VARCHAR(1024) NOT NULL DEFAULT '',
  source           VARCHAR(512)  NOT NULL DEFAULT '',
  url              TEXT,
  publication_date DATE,
  summary          TEXT,
  status           VARCHAR(50)   NOT NULL DEFAULT 'draft',
  atom_object_id   INT           DEFAULT NULL,
  created_at       DATETIME      NOT NULL,
  updated_at       DATETIME      NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
SQL;
        QubitPdo::modify($sql);
    }

    /**
     * Retrieve a single article by primary key.
     *
     * @param  string $id
     * @return QubitHmtArticle|null
     */
    public static function getById($id)
    {
        $stmt = QubitPdo::prepareAndExecute(
            'SELECT * FROM hmt_article WHERE id = ?',
            [$id]
        );
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        return $row ? self::fromRow($row) : null;
    }

    /**
     * Return a paginated list of articles, newest first.
     *
     * @param  int $limit
     * @param  int $offset
     * @return QubitHmtArticle[]
     */
    public static function getList($limit = 25, $offset = 0)
    {
        $stmt = QubitPdo::prepareAndExecute(
            'SELECT * FROM hmt_article ORDER BY created_at DESC LIMIT ? OFFSET ?',
            [(int) $limit, (int) $offset]
        );

        $results = [];
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $results[] = self::fromRow($row);
        }

        return $results;
    }

    /**
     * Persist a new article record.
     * Sets id, created_at, and updated_at automatically if not provided.
     */
    public function insert()
    {
        if (empty($this->id)) {
            $this->id = self::generateId();
        }
        $now = date('Y-m-d H:i:s');
        $this->createdAt = $now;
        $this->updatedAt = $now;

        QubitPdo::prepareAndExecute(
            'INSERT INTO hmt_article
              (id, title, source, url, publication_date, summary, status, atom_object_id, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $this->id,
                $this->title ?? '',
                $this->source ?? '',
                $this->url ?: null,
                $this->publicationDate ?: null,
                $this->summary ?: null,
                $this->status ?? self::STATUS_DRAFT,
                $this->atomObjectId ?: null,
                $this->createdAt,
                $this->updatedAt,
            ]
        );
    }

    /**
     * Persist changes to an existing article record.
     */
    public function update()
    {
        $this->updatedAt = date('Y-m-d H:i:s');

        QubitPdo::prepareAndExecute(
            'UPDATE hmt_article
             SET title = ?, source = ?, url = ?, publication_date = ?, summary = ?,
                 status = ?, atom_object_id = ?, updated_at = ?
             WHERE id = ?',
            [
                $this->title ?? '',
                $this->source ?? '',
                $this->url ?: null,
                $this->publicationDate ?: null,
                $this->summary ?: null,
                $this->status ?? self::STATUS_DRAFT,
                $this->atomObjectId ?: null,
                $this->updatedAt,
                $this->id,
            ]
        );
    }

    /**
     * Delete the article record by id.
     *
     * @param  string $id
     */
    public static function deleteById($id)
    {
        QubitPdo::prepareAndExecute(
            'DELETE FROM hmt_article WHERE id = ?',
            [$id]
        );
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static function fromRow(array $row)
    {
        $obj = new self();
        $obj->id              = $row['id'];
        $obj->title           = $row['title'];
        $obj->source          = $row['source'];
        $obj->url             = $row['url'];
        $obj->publicationDate = $row['publication_date'];
        $obj->summary         = $row['summary'];
        $obj->status          = $row['status'];
        $obj->atomObjectId    = $row['atom_object_id'];
        $obj->createdAt       = $row['created_at'];
        $obj->updatedAt       = $row['updated_at'];

        return $obj;
    }

    private static function generateId()
    {
        // RFC 4122 UUID v4 using cryptographically secure randomness
        $bytes = random_bytes(16);

        // Set version bits (4) and variant bits (RFC 4122)
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);

        // Format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (8-4-4-4-12 hex chars)
        return vsprintf('%s%s%s%s-%s%s-%s%s-%s%s-%s%s%s%s%s%s', str_split(bin2hex($bytes), 2));
    }
}
